services:
  web:
    volumes:
      - "./nginx/localhost.conf:/etc/nginx/conf.d/default.conf"
      - "./app:/var/www/html"
    ports:
      - "8000:80"

  php:
    build:
      dockerfile: Dockerfile
      target: dev
    container_name: harangiert_php
    volumes:
      - "./app:/var/www/html"
      - "./php/99-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    networks:
      default:
        aliases:
          - harangiert-php-fpm
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mariadb:10.11
    ports:
      - "127.0.0.1:${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./db_data:/var/lib/mysql"
    networks:
      default:
        aliases:
          - harangiert-db
