services:
  web:
    volumes:
      - "./nginx/harangiert.de.conf:/etc/nginx/conf.d/harangiert.de.conf"
      - "./app:/var/www/html"
    ports:
      - "8001:80"
    restart: always

  php:
    build:
      dockerfile: Dockerfile
      target: prod
    networks:
      default:
        aliases:
          - harangiert-php-fpm
    env_file:
      - .env
    restart: always